/**
 * Design-token guardrail (chores-web-frontend#23): raw hex colors are not
 * allowed in component CSS — use the custom properties generated by
 * @derekwinters/design-tokens instead. The documented legacy block in
 * src/index.css carries an explicit stylelint-disable.
 */
export default {
  rules: {
    "color-no-hex": true,
  },
};
